speech2txt:
  model_name: facebook/wav2vec2-base-960h
  model_cache: /speech/common_dir/speech2txt
  post_processing_model_cache: /speech/common_dir/text_processing
  post_processing_task: text2text-generation
  device_name: default
  max_len_post_processing: 2048
  sampling_rate: 16000
  vad_mode: 3
  silence_limit_seconds : 3.0
  rate : 16000  
  frame_duration : 30
  channels: 1
  return_tensors: pt
  padding: True


emotion_analysis:
  model_name: text-classification
  model_cache: /speech/common_dir/emotion
  padding: True
  truncation: True
  return_tensors: np
  max_length: 128


tts_ref:
  ref_audio_neutral: /speech/common_dir/txt2speech/ref/neutral.wav
  ref_audio_sad: /speech/common_dir/txt2speech/ref/sad.wav
  ref_audio_happy: /speech/common_dir/txt2speech/ref/happy.wav
  ref_audio_sympathy: /speech/common_dir/txt2speech/ref/sympathy.wav
  ref_audio_anger: /speech/common_dir/txt2speech/ref/anger.wav
  ref_audio_surprise: /speech/common_dir/txt2speech/ref/surprise.wav


txt2speech:
  model_cache: /speech/common_dir/txt2speech/models
  model_config: /speech/common_dir/txt2speech/models/config.json
  output_file_path: /speech/common_dir/output/output.wav
  language: en


llm:
  model_cache: /speech/common_dir/text_gen
  return_tensors: pt
  max_new_tokens: 50
  temperature: 0.1
  repetition_penalty: 1.2
